[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/catalogo"
  to = "/catalogo.html"
  status = 200

[[redirects]]
  from = "/api/catalog"
  to = "/.netlify/functions/catalog"
  status = 200

[[redirects]]
  from = "/api/web-order"
  to = "/.netlify/functions/web-order"
  status = 200

[[redirects]]
  from = "/api/web-order-admin"
  to = "/.netlify/functions/web-order-admin"
  status = 200

[[redirects]]
  from = "/club/:token"
  to = "/club.html?token=:token"
  status = 200
